### ISSUE TITLE
Error:  during github download ... github.com/lib-cov/node

### ISSUE THREAD

**Issue by ds0nt** [babel/duo-babel#10]
Has anyone seen this error?

https://gist.github.com/metagen/3518890c17a09a420357

using io.js:

package.json:
        "duo-babel": "^5.2.0",
        "duo-handlebars": "^0.1.0",
        "co": "^4.5.4"

**Comment by dominicbarnes** [comment]
Those are actually just warnings, but it's telling you that the file in question is pretty big and that babel won't transpile it. (thankfully, these are dependencies that don't need to be transpiled)

A lot of times, you only are transpiling the files that you control, so you can add `onlyLocals` to your duo-babel config to account for that.

If you need granular control over what does/doesn't get transpiled, look at the `only` and `ignore` options. (see [readme](https://github.com/babel/duo-babel#selective-transpiling) for more details)

**Comment by ds0nt** [comment]
thanks: I solved by commenting this line:

// var model = require('component/model');

**Comment by ds0nt** [comment]
Thanks, yeah I saw those. thanks for the plugin ;)
