### ISSUE TITLE
support .jsx?

### ISSUE THREAD

**Issue by kcliu** [babel/duo-babel#12]
i.e., duo -u duo-babel hello.jsx

**Comment by dominicbarnes** [comment]
Oh, you need to cover the extension `.jsx` ?

**Comment by kcliu** [comment]
yes, since I can do `babel hello.jsx`, it would be nice if compatible with babel

**Comment by dominicbarnes** [comment]
Sounds good, I'll go ahead and include other extensions like `.es` and `.es6` since they are supported by babel as well.

**Comment by kcliu** [comment]
awesome!  thanks
