### ISSUE TITLE
duo-babel is broken

### ISSUE THREAD

**Issue by poying** [babel/duo-babel#14]
The `only` option is broken because the implementation of `util.shouldIgnore` in babel was changed. (https://github.com/babel/babel/commit/c9286a1de1f7ef8e88396414c23233918d2f868b)

**Comment by dominicbarnes** [comment]
Can you be more specific? What is broken exactly?

**Comment by poying** [comment]
@dominicbarnes `npm test` is failed.

**Comment by dominicbarnes** [comment]
Ok, I've verified that this is broken and will work on a fix asap.

**Comment by dominicbarnes** [comment]
I've got the tests passing again with b85884ffb0bf3cd3cb6db347c0186e1536c73736. Feel free to re-open if this doesn't fix the problem you are having.
